export const GET_ROADMAPS = "GET_ROADMAPS";
export const ADD_ROADMAP = "ADD_ROADMAPS";
export const DELETE_ROADMAP = "DELETE_ROADMAP";
export const ROADMAPS_LOADING = "ROADMAPS_LOADING";
export const GET_ROADMAP_BY_ID = "GET_ROADMAP_BY_ID";
